apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shlink-web.fullname" . }}
  labels:
    {{- include "shlink-web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "shlink-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "shlink-web.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "shlink-web.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SHLINK_SERVER_URL
              value: {{ .Values.env.SHLINK_SERVER_URL | quote }}
            - name: SHLINK_SERVER_NAME
              value: {{ .Values.env.SHLINK_SERVER_NAME | quote }}
            {{- if .Values.externalSecret.enabled }}
            - name: SHLINK_SERVER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalSecret.name | quote }}
                  key: {{ .Values.externalSecret.key | quote }}
            {{- else }}
            - name: SHLINK_SERVER_API_KEY
              value: {{ .Values.env.SHLINK_SERVER_API_KEY | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 60
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
