name: Check for new Helm Chart Versions

on:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v40 # Using a more stable major version
        with:
          token: ${{ secrets.GITHUB_TOKEN }}