name: Renovate

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v40 # Using a more stable major version
        with:
          # The token is required to create issues and PRs.
          # The GITHUB_TOKEN is automatically created by GitHub Actions.
          token: ${{ secrets.GITHUB_TOKEN }}