name: Renovate

on:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v43.0.16
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ONBOARDING: "false"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          